### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by landsman** [studioartcz/colombo#1]
check:
- [ ] right HTTP => HTTPS redirects with 301
- [ ] HTT2
- [ ] enabled GZIP
- [ ] minified javascripts, CSS, source code
- [ ] page size, code size
- [ ] code update (composer versions vs. updates, [Rector](https://github.com/RectorPHP/Rector), ...)
- [ ] ... what else?
make suggestions for fixs

**Comment by smety** [comment]
- [ ] JS Lint checker?
- [ ] Selenium?

**Comment by landsman** [comment]
- [ ] Some code checker, syntax changer like: https://github.com/dg/php54-arrays

**Comment by landsman** [comment]
- [ ] Two empty lines before return
- [ ] Two empty lines between methods
